from __future__ import annotations

import threading

from app.services import db


class UserStore:
    def __init__(self, path: str | None = None):
        self.path = path or "users"
        self._lock = threading.Lock()
        self._ready = False

    def _connect(self):
        return db.connect(self.path)

    def _ensure_ready(self) -> None:
        if self._ready:
            return
        with self._lock:
            if self._ready:
                return
            with self._connect() as connection:
                connection.execute(
                    """
                    CREATE TABLE IF NOT EXISTS users (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username TEXT NOT NULL,
                        password_hash TEXT NOT NULL,
                        created_at TEXT NOT NULL
                    )
                    """
                )
                connection.execute(
                    "CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_lower "
                    "ON users(lower(username))"
                )
                connection.commit()
            self._ready = True

    def create(self, username: str, password_hash: str, created_at: str) -> bool:
        self._ensure_ready()
        try:
            with self._lock, self._connect() as connection:
                connection.execute(
                    db.q("INSERT INTO users(username, password_hash, created_at) VALUES(?,?,?)"),
                    (username, password_hash, created_at),
                )
                connection.commit()
        except Exception as exc:
            if not db.is_unique_violation(exc):
                raise
            return False
        return True

    def get(self, username: str) -> dict | None:
        self._ensure_ready()
        with self._lock, self._connect() as connection:
            sql = "SELECT id, username, password_hash, created_at FROM users WHERE lower(username)=lower(%s)"
            row = connection.execute(db.q(sql), (username,)).fetchone()
        return dict(row) if row else None


_USER_STORE = UserStore()


def get_user_store() -> UserStore:
    return _USER_STORE
