[theme]
base = "dark"
primaryColor = "#c9974c"
backgroundColor = "#10121b"
secondaryBackgroundColor = "#171a26"
textColor = "#eceef5"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
